version: '3.8'

services:
  boringai-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SEARCHAPI_API_KEY=${SEARCHAPI_API_KEY}
      - DEFAULT_REFERER_URL=${DEFAULT_REFERER_URL}
      - DEFAULT_SITE_NAME=${DEFAULT_SITE_NAME}
      - DEFAULT_API_PROVIDER=${DEFAULT_API_PROVIDER}
      - DEFAULT_OPENAI_MODEL=${DEFAULT_OPENAI_MODEL}
      - DEFAULT_OPENROUTER_MODEL=${DEFAULT_OPENROUTER_MODEL}
    volumes:
      - .:/app
