version: '3.8'

services:
  app:
    build: .
    ports:
      - "9975:9975"
    volumes:
      - .:/app  # Mount the current folder into the container
    environment:
      - FLASK_ENV=development
      - FLASK_APP=boring_ai_gmaps_analytics.app
      - PYTHONPATH=/app  # Add this line to include the project directory in Python's module search path
